title = "openBVE Documentation"
theme = "openbve_documentation"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
removePathAccents = true

relativeURLs = true
uglyURLs = true

disableKinds = ["page", "404", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

[params]
  logoimage = "/images/logo.png"

[blackfriday]
  hrefTargetBlank = true
  extensions = ["laxHtmlBlocks"]

[languages]
[languages.ca]
contentDir = "content/ca"
languageName = "Català"
weight = 1
[languages.en]
contentDir = "content/en"
languageName = "English"
weight = 2
[languages.es_MX]
contentDir = "content/es_MX"
languageName = "Mexican Spanish"
weight = 3
[languages.fr]
contentDir = "content/fr"
languageName = "French"
weight = 4
[languages.ja]
contentDir = "content/ja"
languageName = "日本語"
weight = 5
[languages.zh]
contentDir = "content/zh"
languageName = "Chinese"
weight = 6
[languages.ko]
contentDir = "content/ko"
languageName = "한국어"
weight = 7
[languages.hu]
contentDir = "content/hu"
languageName = "Magyar"
weight = 8
[languages.id]
contentDir = "content/id"
languageName = "Indonesian"
weight = 9