name: siteUpdate
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.66.0"

      - name: Build
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: ./BuildScript.sh